### PR TITLE
Add Static Content only if required

### LINKED ISSUE #2334: Install injects staticContent section a second time to webconfig
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Installation

**Current behavior**
Current web.config has already a staticContent section.
When 2sxc installs, it adds it a second time, breaking the server installation.

It is super easy to discover and to fix, and I already know that now for a too long time. 
Installing 2sxc and editing web.config was already part of my installation recipe.

Problem is this section in the manifest:
```xml
        <node path="/configuration/system.webServer" targetpath="/configuration/system.webServer/staticContent" action="update" collision="ignore">
          <staticContent>
            <remove fileExtension=".webp" />
            <mimeMap fileExtension=".webp" mimeType="image/webp" />
          </staticContent>
        </node>
```

**What is the motivation of this report**
I am going to submit a PR.

### PR DESCRIPTION
**Pull request by SCullman**
Fixes #2334
Now also in sync with [DNN](https://github.com/dnnsoftware/Dnn.Platform/blob/master/DNN%20Platform/Website/Install/Config/09.06.02.config)

### CODE REVIEW

**Comment by iJungleboy** [comment]
I believe this would only work in newer DNNs, which already have WebP support. it would fail in DNN 7 / 8 which don't have it yet. That's why it has these two-steps

1. remove if already exists (to avoid duplicates)
2. Add

Or do you see a better way

Many thanks!

**Comment by SCullman** [comment]
I did the following test 

- Installed a fresh DNN9.8. 
- Removed the staticContent section in web.config.
- Installed 2sxc with my changed manifest
- opened web.config again:
```
  <staticContent>
    <remove fileExtension=".webp" />
    <mimeMap fileExtension=".webp" mimeType="image/webp" />
  </staticContent>
```
The code to infect the elements for webp are still part of the manifest. And this should work in DNN7 too!

**Comment by iJungleboy** [comment]
The problem is as follows

1. in DNN 7 the webp is missing, so the manifest must add it
2. but in DNN 9 the webp is already added, so to ensure nothing breaks, it must first remove it

In your example I believe it will neither add nor remove, so it would work in DNN 9, but not in DNN 7.

**Comment by SCullman** [comment]
In both cases, for DNN 7 and DNN 9, it will result in 

```xml
  <staticContent>
    <remove fileExtension=".webp" />
    <mimeMap fileExtension=".webp" mimeType="image/webp" />
  </staticContent>
  ```
  within web.config.
  
  And this is valid for both, isn't it?

**Comment by SCullman** [comment]
In case there is already a staticContent section within web.config handling other file extensions, it will only add the two entries required for webp. 
Currently, without the PR, it would add a second staticContent section in web.config causing the system to fail with a yellow screen of death (or a custom error)

**Comment by iJungleboy** [comment]
Ok, I think understand now. Sorry for the confusion. 
I need to get it into develop (not master), so give me a few moments to figure out how to accept this without causing new problems :).

**Comment by iJungleboy** [comment]
thx!

**Pull request merged**
